<?php

// controllers/EmailWorker.php
class EmailWorker extends CI_Controller

{




    public function __construct()
    {
        parent::__construct();
        $this->load->model('LeadModel');
        $this->load->library('email');
        $this->load->model('Comman_model');
        $this->load->model('Common_model');
        date_default_timezone_set('Asia/Kolkata');
    }


    public function sendLeadEmail($leadID = null, $IsvaluableGuest = '')
    {




        if (!$leadID) show_404();

        $this->load->model('Comman_model');
        $this->load->model('Mail_model');

        $leadData = $this->Comman_model->getdata('leads', ['id' => $leadID]);
        if (!$leadData) {
            log_message('error', 'Lead not found for ID: ' . $leadID);
            show_404();
        }




        $hotel = $this->Comman_model->getdata('hotel_admin', ['hotel_id' => $leadData->property ?? 0]);



        $department = $this->Comman_model->getdata('departments', ['department_id' => $leadData->type ?? 0]);


        $hotel_id = $leadData->property ?? 0;
        $department_id = $leadData->type ?? 0;

        $hotel_id = $leadData->property ?? 0;
        $department_id = $leadData->type ?? 0;



        // Join staff with mapping to get all emails
        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join('staff_hotel_department_mapping', 'staff_members.id = staff_hotel_department_mapping.staff_id');
        $this->db->where('staff_hotel_department_mapping.level', 1);
        $this->db->where('staff_hotel_department_mapping.hotel_id', $hotel_id);
        $this->db->where('staff_hotel_department_mapping.department_id', $department_id);

        $query = $this->db->get();
        $result = $query->result();

        $emails = array_column($result, 'email'); // extract email list

        $hotel_name = isset($hotel->hotel_name) ? $hotel->hotel_name : 'N/A';
        $department_name = isset($department->department_name) ? $department->department_name : 'N/A';



        $subject = 'New Lead Registered: ' . ($leadData->user_name ?? 'Unknown') . ' for ' . ($department_name ?? 'Unknown') . ' - ' . date('d M Y', strtotime($leadData->created_at ?? date('Y-m-d')));


        if ($IsvaluableGuest) {
            $subject = 'New Lead From Valuable Guest: ' . ($leadData->user_name ?? 'Unknown') . ' for ' . ($department_name ?? 'Unknown') . ' - ' . date('d M Y', strtotime($leadData->created_at ?? date('Y-m-d')));
        }

        $message = '
        <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; background-color: #f9f9f9;">
            <h2 style="color: #2c3e50;">New Lead Notification</h2>
            <p>A new lead has been registered with the following details:</p>
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                <tr><td><strong>Name</strong></td><td>' . htmlspecialchars($leadData->user_name ?? '') . '</td></tr>
                <tr><td><strong>Phone</strong></td><td>' . htmlspecialchars($leadData->phone_number ?? '') . '</td></tr>
                <tr><td><strong>Email</strong></td><td>' . htmlspecialchars($leadData->email ?? '') . '</td></tr>
                <tr><td><strong>Query</strong></td><td>' . nl2br(htmlspecialchars($leadData->query ?? '')) . '</td></tr>
                <tr><td><strong>Property</strong></td><td>' . htmlspecialchars($hotel_name) . '</td></tr>
                <tr><td><strong>Department</strong></td><td>' . htmlspecialchars($department_name) . '</td></tr>
                <tr><td><strong>Source</strong></td><td>' . htmlspecialchars($leadData->user_channel) . '</td></tr>

                <tr><td><strong>Created At</strong></td><td>' . date('d M Y, h:i A', strtotime($leadData->created_at ?? date('Y-m-d H:i:s'))) . '</td></tr>
            </table>
            <p style="margin-top: 20px; font-size: 13px; color: #888;">This is an automated message generated by the lead management system.</p>
        </div>';


        if (count($emails) > 0) {
            $result = $this->Mail_model->sendMailSMTP_uv('', $emails, $subject, $message, "", $IsvaluableGuest);
        }


        if ($result === true) {
            log_message('info', "Lead email sent successfully for lead ID: $leadID");
        } else {
            log_message('error', "Lead email failed for lead ID: $leadID");
        }
    }


    public function sendLeadEmailToassigned_person_email($leadID = null, $IsvaluableGuest = '')
    {




        if (!$leadID) show_404();

        $this->load->model('Comman_model');
        $this->load->model('Mail_model');

        $leadData = $this->Comman_model->getdata('leads', ['id' => $leadID]);
        if (!$leadData) {
            log_message('error', 'Lead not found for ID: ' . $leadID);
            show_404();
        }




        $hotel = $this->Comman_model->getdata('hotel_admin', ['hotel_id' => $leadData->property ?? 0]);



        $department = $this->Comman_model->getdata('departments', ['department_id' => $leadData->type ?? 0]);


        $hotel_id = $leadData->property ?? 0;
        $department_id = $leadData->type ?? 0;

        $hotel_id = $leadData->property ?? 0;
        $department_id = $leadData->type ?? 0;



        // Join staff with mapping to get all emails
        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join('staff_hotel_department_mapping', 'staff_members.id = staff_hotel_department_mapping.staff_id');
        $this->db->where('staff_hotel_department_mapping.level', 1);
        $this->db->where('staff_hotel_department_mapping.hotel_id', $hotel_id);
        $this->db->where('staff_hotel_department_mapping.department_id', $department_id);

        $query = $this->db->get();
        $result = $query->result();

        $assigned_to_id = $leadData->assigned_to;
        $assigned_person_user_role = $leadData->assigned_person_user_role;

        $assigned_person_email = '';

        if ($assigned_person_user_role == 'super_admin') {

            $user = $this->db->select('email')
                ->from('super_admin')
                ->where('id', $assigned_to_id)
                ->get()
                ->row();

            if ($user) {
                $assigned_person_email = $user->email;
            }
        } elseif ($assigned_person_user_role == 'admin') {

            $user = $this->db->select('email')
                ->from('hotel_admins')
                ->where('id', $assigned_to_id)
                ->get()
                ->row();

            if ($user) {
                $assigned_person_email = $user->email;
            }
        } elseif ($assigned_person_user_role == 'agent') {

            $user = $this->db->select('email')
                ->from('staff_members')
                ->where('id', $assigned_to_id)
                ->get()
                ->row();

            if ($user) {
                $assigned_person_email = $user->email;
            }
        }



        $hotel_name = isset($hotel->hotel_name) ? $hotel->hotel_name : 'N/A';
        $department_name = isset($department->department_name) ? $department->department_name : 'N/A';



        $subject = 'New Lead Registered: ' . ($leadData->user_name ?? 'Unknown') . ' for ' . ($department_name ?? 'Unknown') . ' - ' . date('d M Y', strtotime($leadData->created_at ?? date('Y-m-d')));


        if ($IsvaluableGuest) {
            $subject = 'New Lead From Valuable Guest: ' . ($leadData->user_name ?? 'Unknown') . ' for ' . ($department_name ?? 'Unknown') . ' - ' . date('d M Y', strtotime($leadData->created_at ?? date('Y-m-d')));
        }

        $message = '
        <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; background-color: #f9f9f9;">
            <h2 style="color: #2c3e50;">New Lead Notification</h2>
            <p>A new lead has been registered with the following details:</p>
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                <tr><td><strong>Name</strong></td><td>' . htmlspecialchars($leadData->user_name ?? '') . '</td></tr>
                <tr><td><strong>Phone</strong></td><td>' . htmlspecialchars($leadData->phone_number ?? '') . '</td></tr>
                <tr><td><strong>Email</strong></td><td>' . htmlspecialchars($leadData->email ?? '') . '</td></tr>
                <tr><td><strong>Query</strong></td><td>' . nl2br(htmlspecialchars($leadData->query ?? '')) . '</td></tr>
                <tr><td><strong>Property</strong></td><td>' . htmlspecialchars($hotel_name) . '</td></tr>
                <tr><td><strong>Department</strong></td><td>' . htmlspecialchars($department_name) . '</td></tr>
                <tr><td><strong>Source</strong></td><td>' . htmlspecialchars($leadData->user_channel) . '</td></tr>

                <tr><td><strong>Created At</strong></td><td>' . date('d M Y, h:i A', strtotime($leadData->created_at ?? date('Y-m-d H:i:s'))) . '</td></tr>
            </table>
            <p style="margin-top: 20px; font-size: 13px; color: #888;">This is an automated message generated by the lead management system.</p>
        </div>';



        $result = $this->Mail_model->sendMailSMTP_uv('', [$assigned_person_email], $subject, $message, "", $IsvaluableGuest);



        if ($result === true) {
            log_message('info', "Lead email sent successfully for lead ID: $leadID");
        } else {
            log_message('error', "Lead email failed for lead ID: $leadID");
        }
    }




    public function sendEscalationL1($lead_id = null)
    {
        if (!$lead_id) return;

        $this->load->model(['Comman_model', 'Mail_model']);

        $lead = $this->LeadModel->get_lead_with_property_and_department($lead_id);


        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join('staff_hotel_department_mapping', 'staff_members.id = staff_hotel_department_mapping.staff_id');
        $this->db->where('staff_hotel_department_mapping.level', 1);
        $this->db->where('staff_hotel_department_mapping.hotel_id', $lead->property);
        $this->db->where('staff_hotel_department_mapping.department_id', $lead->type);
        $query = $this->db->get();
        $result = $query->result();

        $emails = array_column($result, 'email'); // extract email list

        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join('staff_hotel_department_mapping', 'staff_members.id = staff_hotel_department_mapping.staff_id');
        $this->db->where('staff_hotel_department_mapping.level', 2);
        $this->db->where('staff_hotel_department_mapping.hotel_id', $lead->property);
        $this->db->where('staff_hotel_department_mapping.department_id', $lead->type);
        $query = $this->db->get();
        $result = $query->result();

        $cc_emails = array_column($result, 'email'); // extract email list





        $subject = "Level 1 Escalation: Lead Pending Follow-up";
        $message = $this->buildEscalationEmailBody($lead, 1);

        $this->Mail_model->sendMailSMTP_uv('', $emails, $subject, $message, $cc_emails);
    }

    public function sendEscalationL2($lead_id = null)
    {
        if (!$lead_id) return;

        $this->load->model(['Comman_model', 'Mail_model']);

        $lead = $this->LeadModel->get_lead_with_property_and_department($lead_id);





        $emails = [$lead->hotel_admin_email]; // extract email list

        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join('staff_hotel_department_mapping', 'staff_members.id = staff_hotel_department_mapping.staff_id');
        $this->db->where('staff_hotel_department_mapping.hotel_id', $lead->property);
        $this->db->where('staff_hotel_department_mapping.department_id', $lead->type);
        $query = $this->db->get();
        $result = $query->result();

        $cc_emails = array_column($result, 'email');




        $subject = "Level 2 Escalation: Immediate Attention Required";
        $message = $this->buildEscalationEmailBody($lead, 2);

        $this->Mail_model->sendMailSMTP_uv('', $emails, $subject, $message, $cc_emails);
    }






    public function sendEscalationL3($lead_id = null)
    {
        if (!$lead_id) return;

        $this->load->model(['Comman_model', 'Mail_model']);

        $lead = $this->LeadModel->get_lead_with_property_and_department($lead_id);


        $emails = [''];

        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join('staff_hotel_department_mapping', 'staff_members.id = staff_hotel_department_mapping.staff_id');
        $this->db->where('staff_hotel_department_mapping.hotel_id', $lead->property);
        $this->db->where('staff_hotel_department_mapping.department_id', $lead->type);
        $query = $this->db->get();
        $result = $query->result();

        $cc_emails = array_column($result, 'email'); // extract email list



        $extra_email = $lead->hotel_admin_email;

        $cc_emails[] = $extra_email;

        // Remove duplicates
        $cc_emails = array_values(array_unique($cc_emails));



        $subject = "Level 3 Escalation: SLA Breach";
        $message = $this->buildEscalationEmailBody($lead, 3);

        $this->Mail_model->sendMailSMTP_uv('', $emails, $subject, $message, $cc_emails);
    }


    private function buildEscalationEmailBody($leadData, $level)
    {
        $level_text = '';
        $level_color = '#e67e22';

        switch ($level) {
            case 1:
                $level_text = 'Level 1 Escalation – Follow-up Pending';
                break;

            case 2:
                $level_text = 'Level 2 Escalation – Immediate Attention Required';
                $level_color = '#e74c3c';
                break;

            case 3:
                $level_text = 'Level 3 Escalation – SLA Breach';
                $level_color = '#fa0a0a';
                break;
        }

        return '
    <div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; background-color: #f9f9f9;">
        <h2 style="color: ' . $level_color . ';">' . $level_text . '</h2>

        <p>The following lead has not been attended within the defined SLA:</p>

        <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr><td><strong>Name</strong></td><td>' . htmlspecialchars($leadData->user_name ?? '') . '</td></tr>
            <tr><td><strong>Phone</strong></td><td>' . htmlspecialchars($leadData->phone_number ?? '') . '</td></tr>
            <tr><td><strong>Email</strong></td><td>' . htmlspecialchars($leadData->email ?? '') . '</td></tr>
            <tr><td><strong>Query</strong></td><td>' . nl2br(htmlspecialchars($leadData->query ?? '')) . '</td></tr>
            <tr><td><strong>Property</strong></td><td>' . htmlspecialchars($leadData->hotel_name) . '</td></tr>
            <tr><td><strong>Department</strong></td><td>' . htmlspecialchars($leadData->department_name) . '</td></tr>
            <tr><td><strong>Source</strong></td><td>' . htmlspecialchars($leadData->user_channel ?? '') . '</td></tr>
            <tr><td><strong>Lead Created At</strong></td>
                <td>' . date('d M Y, h:i A', strtotime($leadData->created_at ?? date('Y-m-d H:i:s'))) . '</td>
            </tr>
        </table>

        <p style="margin-top: 20px; font-size: 13px; color: #888;">
            This is an automated escalation email generated by the Lead Management System.
        </p>
    </div>';
    }


    private function getEscalationEmails($lead, $level)
    {
        $this->db->select('staff_members.email');
        $this->db->from('staff_members');
        $this->db->join(
            'staff_hotel_department_mapping',
            'staff_members.id = staff_hotel_department_mapping.staff_id'
        );
        $this->db->where('staff_hotel_department_mapping.hotel_id', $lead->property);
        $this->db->where('staff_hotel_department_mapping.department_id', $lead->type);
        $this->db->where('staff_hotel_department_mapping.escalation_level <=', $level);

        return array_column($this->db->get()->result(), 'email');
    }
}
